export const topics = {
  business: [
    "How can small businesses compete with large corporations?",
    "What leadership style is most effective in times of crisis?",
    "Should companies prioritize profit or social responsibility?",
    "How has remote work changed business culture?",
    "What role does innovation play in business success?",
    "How important is workplace diversity for company performance?",
    "Should businesses be required to disclose their environmental impact?",
    "What makes a successful entrepreneur?",
    "How has e-commerce changed traditional retail?",
    "Should workers have more say in company decisions?",
    "What is the future of the gig economy?",
    "How do you build trust in business relationships?",
    "Should businesses be allowed to operate globally without restrictions?",
    "What role does marketing play in consumer behavior?",
    "How important is customer service in business success?",
    "Should companies be held responsible for their supply chain practices?",
    "What is the impact of automation on job creation?",
    "How do you balance risk and reward in business?",
    "Should businesses prioritize short-term or long-term profits?",
    "What makes a workplace culture successful?",
    "How important is brand reputation in modern business?",
    "Should businesses be required to support local communities?",
    "What role does networking play in career advancement?",
    "How do you measure business success beyond financial metrics?",
    "Should companies have mandatory diversity quotas?",
    "What is the importance of work-life balance for productivity?",
    "How has social media changed business communication?",
    "Should businesses be transparent about their decision-making processes?",
    "What role does competition play in driving innovation?",
    "How important is employee satisfaction for business success?",
    "Should businesses be required to provide mental health support?",
    "What is the future of office spaces?",
    "How do you build a sustainable business model?",
    "Should businesses be allowed to collect unlimited customer data?",
    "What role does corporate governance play in business ethics?",
    "How important is continuous learning in professional development?",
    "Should businesses be required to pay living wages?",
    "What is the impact of globalization on local businesses?",
    "How do you create effective team collaboration?",
    "Should businesses prioritize customer satisfaction over profit margins?",
    "What role does technology play in business efficiency?",
    "How important is financial literacy for business owners?",
    "Should businesses be required to report their carbon footprint?",
    "What makes a successful business partnership?",
    "How do you handle failure in business?",
    "Should businesses be allowed to operate without government regulation?",
    "What is the importance of adaptability in business strategy?",
    "How do you build customer loyalty in competitive markets?",
    "Should businesses be required to provide parental leave policies?",
    "What role does intuition play in business decision-making?",
  ],
  technology: [
    "How has artificial intelligence changed the workplace?",
    "Should technology companies be broken up to prevent monopolies?",
    "What are the ethical implications of facial recognition technology?",
    "How do we balance technological progress with privacy concerns?",
    "Should social media platforms be regulated like public utilities?",
    "What role should technology play in education?",
    "How has remote work technology changed employment patterns?",
    "Should there be limits on screen time for children?",
    "What is the future of cryptocurrency and digital payments?",
    "How do we protect against cybersecurity threats?",
    "Should robots replace humans in dangerous jobs?",
    "What are the implications of genetic engineering technology?",
    "How has technology changed human communication?",
    "Should there be universal access to high-speed internet?",
    "What role does technology play in climate change solutions?",
    "How do we ensure AI systems are fair and unbiased?",
    "Should personal data be considered a human right?",
    "What is the impact of automation on job markets?",
    "How has technology changed the healthcare industry?",
    "Should there be age restrictions on social media platforms?",
    "What role does technology play in democratic processes?",
    "How do we prepare the workforce for technological changes?",
    "Should tech companies be responsible for content moderation?",
    "What are the benefits and risks of smart city technology?",
    "How has technology affected mental health and wellbeing?",
    "Should there be limits on artificial intelligence development?",
    "What role does technology play in creative industries?",
    "How do we ensure digital equity across different communities?",
    "Should governments have backdoor access to encrypted communications?",
    "What is the future of virtual and augmented reality?",
    "How has technology changed the way we consume news?",
    "Should there be mandatory digital literacy education?",
    "What are the implications of quantum computing?",
    "How do we manage electronic waste and sustainability?",
    "Should there be international standards for technology ethics?",
    "What role does technology play in scientific research?",
    "How has technology changed transportation and mobility?",
    "Should there be limits on data collection by tech companies?",
    "What is the impact of technology on traditional industries?",
    "How do we ensure technology serves humanity's best interests?",
    "Should there be global governance of emerging technologies?",
    "What role does technology play in addressing inequality?",
    "How has technology changed the nature of work itself?",
    "Should there be right to disconnect from technology?",
    "What are the implications of brain-computer interfaces?",
    "How do we balance innovation with safety in technology?",
    "Should there be mandatory ethics training for tech developers?",
    "What role does technology play in sustainable development?",
    "How has technology changed human relationships and intimacy?",
    "Should there be limits on surveillance technology use?",
  ],
  politics: [
    "Should voting be mandatory in democratic countries?",
    "What is the ideal balance between security and freedom?",
    "Should politicians have term limits?",
    "How important is it for leaders to have political experience?",
    "Should the voting age be lowered to 16?",
    "What role should money play in political campaigns?",
    "Should countries prioritize national interests over global cooperation?",
    "How important is transparency in government operations?",
    "Should there be limits on political campaign spending?",
    "What is the role of civil disobedience in democracy?",
    "Should politicians be allowed to hold investments while in office?",
    "How do we balance majority rule with minority rights?",
    "Should there be mandatory civics education in schools?",
    "What role should the media play in political discourse?",
    "Should political parties receive public funding?",
    "How important is it for politicians to keep campaign promises?",
    "Should there be mandatory cooling-off periods for former politicians?",
    "What is the ideal size and scope of government?",
    "Should referendums be used more frequently for major decisions?",
    "How do we prevent foreign interference in domestic politics?",
    "Should there be mandatory diversity requirements in government?",
    "What role should experts play in political decision-making?",
    "Should political debates be mandatory for all candidates?",
    "How important is it for politicians to compromise?",
    "Should there be limits on lobbying activities?",
    "What is the role of protest in democratic society?",
    "Should politicians be required to release their tax returns?",
    "How do we ensure equal representation in government?",
    "Should there be mandatory retirement ages for politicians?",
    "What role should religion play in politics?",
    "Should gerrymandering be illegal?",
    "How important is international cooperation in solving global problems?",
    "Should there be mandatory mental health evaluations for politicians?",
    "What is the ideal relationship between federal and local government?",
    "Should political appointments be subject to public approval?",
    "How do we balance free speech with preventing harmful misinformation?",
    "Should there be mandatory cooling-off periods before politicians can become lobbyists?",
    "What role should citizens play in policy-making beyond voting?",
    "Should there be limits on the number of terms a politician can serve?",
    "How important is it for politicians to have diverse life experiences?",
    "Should political parties be publicly funded to reduce corporate influence?",
    "What is the role of compromise in effective governance?",
    "Should there be mandatory financial disclosure for all public officials?",
    "How do we ensure accountability in government spending?",
    "Should there be citizen juries for political ethics violations?",
    "What role should youth voices play in political decision-making?",
    "Should there be mandatory training for new politicians?",
    "How important is it for politicians to listen to their constituents?",
    "Should there be limits on political advertising during elections?",
    "What is the ideal balance between privacy and government transparency?",
  ],
  philosophy: [
    "Is it more important to be happy or to live a meaningful life?",
    "What defines a 'good' person in today's world?",
    "Is there such a thing as objective truth?",
    "How should we balance individual rights with collective responsibility?",
    "What is the purpose of human existence?",
    "Is free will an illusion or reality?",
    "Should we judge people by their intentions or their actions?",
    "What is the relationship between knowledge and wisdom?",
    "Is it possible to be truly selfless?",
    "What role does suffering play in human development?",
    "Is morality universal or culturally relative?",
    "What is the nature of consciousness?",
    "Should we prioritize reason or emotion in decision-making?",
    "What is the meaning of justice?",
    "Is progress always good for humanity?",
    "What is the relationship between mind and body?",
    "Should we live as if we're immortal or mortal?",
    "What is the source of human dignity?",
    "Is there a fundamental human nature?",
    "What role does doubt play in the pursuit of knowledge?",
    "Should we accept uncertainty or seek absolute answers?",
    "What is the relationship between language and thought?",
    "Is beauty objective or subjective?",
    "What is the role of tradition in modern society?",
    "Should we trust our intuition or rely on evidence?",
    "What is the nature of personal identity over time?",
    "Is it possible to live without any beliefs?",
    "What is the relationship between power and responsibility?",
    "Should we judge historical figures by modern standards?",
    "What is the role of hope in human life?",
    "Is solitude necessary for self-understanding?",
    "What is the difference between needs and wants?",
    "Should we strive for perfection or accept imperfection?",
    "What is the role of failure in personal growth?",
    "Is it possible to know yourself completely?",
    "What is the relationship between freedom and responsibility?",
    "Should we live in the present or plan for the future?",
    "What is the nature of love and friendship?",
    "Is it better to be feared or loved?",
    "What is the role of courage in moral action?",
    "Should we follow rules or trust our judgment?",
    "What is the relationship between creativity and destruction?",
    "Is it possible to be neutral in moral conflicts?",
    "What is the role of forgiveness in human relationships?",
    "Should we seek to understand or to be understood?",
    "What is the nature of time and change?",
    "Is it possible to live without regrets?",
    "What is the relationship between simplicity and complexity?",
    "Should we embrace or resist change?",
    "What is the ultimate test of character?",
  ],
  environment: [
    "Should individuals make personal sacrifices to combat climate change?",
    "How can developing countries balance growth with environmental protection?",
    "Should governments ban single-use plastics entirely?",
    "What role should nuclear energy play in our future?",
    "Should environmental protection take priority over economic growth?",
    "How important is individual action versus systemic change?",
    "Should there be limits on population growth for environmental reasons?",
    "What responsibility do wealthy nations have for global climate action?",
    "Should we focus on adaptation or prevention of climate change?",
    "How can we make sustainable living more accessible to everyone?",
    "Should companies be required to pay for their environmental impact?",
    "What role should technology play in environmental solutions?",
    "Should there be carbon taxes on high-emission activities?",
    "How important is biodiversity preservation versus human development?",
    "Should we prioritize local or global environmental initiatives?",
    "What role should renewable energy play in our energy mix?",
    "Should there be mandatory environmental education in schools?",
    "How can we balance food security with sustainable agriculture?",
    "Should there be limits on resource consumption per person?",
    "What responsibility do consumers have for environmental protection?",
    "Should we invest in geoengineering solutions to climate change?",
    "How important is wilderness preservation in modern society?",
    "Should there be international environmental courts?",
    "What role should indigenous knowledge play in environmental policy?",
    "Should we prioritize climate change over other environmental issues?",
    "How can we make environmental sustainability economically attractive?",
    "Should there be limits on industrial pollution even if it costs jobs?",
    "What role should forests play in climate change mitigation?",
    "Should we ban fossil fuel extraction entirely?",
    "How important is ocean conservation for global sustainability?",
    "Should there be mandatory green building standards?",
    "What role should urban planning play in environmental protection?",
    "Should we prioritize efficiency or renewable energy sources?",
    "How can we address environmental justice and inequality?",
    "Should there be limits on water usage in drought-prone areas?",
    "What role should recycling play in waste management?",
    "Should we invest in space exploration or Earth conservation?",
    "How important is soil health for environmental sustainability?",
    "Should there be mandatory environmental impact assessments?",
    "What role should public transportation play in reducing emissions?",
    "Should we focus on individual or collective environmental responsibility?",
    "How can we balance environmental protection with human comfort?",
    "Should there be limits on meat consumption for environmental reasons?",
    "What role should green technology play in developing countries?",
    "Should environmental concerns override property rights?",
    "How important is environmental education for behavior change?",
    "Should we prioritize prevention or cleanup of environmental damage?",
    "What role should natural disasters play in environmental policy?",
    "Should there be global environmental governance?",
    "How can we make environmental protection a human priority?",
  ],
  health: [
    "Should healthcare be a universal right or earned privilege?",
    "How important is mental health compared to physical health?",
    "Should unhealthy lifestyle choices affect insurance coverage?",
    "What role should alternative medicine play in healthcare?",
    "Should there be mandatory vaccination for all diseases?",
    "How do we balance patient autonomy with medical expertise?",
    "Should healthcare providers focus on treatment or prevention?",
    "What role should technology play in personal health monitoring?",
    "Should there be limits on medical interventions to extend life?",
    "How important is health education in schools?",
    "Should genetic testing be mandatory for certain conditions?",
    "What role should nutrition play in healthcare policy?",
    "Should there be limits on pharmaceutical company profits?",
    "How do we address health disparities across different communities?",
    "Should employers be responsible for employee health?",
    "What role should exercise play in healthcare prevention?",
    "Should there be mandatory mental health screenings?",
    "How important is sleep for overall health and productivity?",
    "Should there be limits on healthcare spending per patient?",
    "What role should patients play in their own healthcare decisions?",
    "Should there be mandatory health insurance for everyone?",
    "How do we balance medical privacy with public health needs?",
    "Should there be limits on medical malpractice lawsuits?",
    "What role should stress management play in healthcare?",
    "Should there be mandatory organ donation programs?",
    "How important is environmental health for individual wellbeing?",
    "Should there be limits on cosmetic medical procedures?",
    "What role should telemedicine play in healthcare delivery?",
    "Should there be mandatory health education for all adults?",
    "How do we balance medical innovation with healthcare costs?",
    "Should there be limits on antibiotic use to prevent resistance?",
    "What role should community health programs play?",
    "Should there be mandatory disclosure of medical errors?",
    "How important is cultural competency in healthcare?",
    "Should there be limits on medical testing to reduce costs?",
    "What role should peer support play in mental health treatment?",
    "Should there be mandatory wellness programs at work?",
    "How do we address the social determinants of health?",
    "Should there be limits on medical advertising to consumers?",
    "What role should family involvement play in patient care?",
    "Should there be mandatory reporting of domestic violence?",
    "How important is health literacy for patient outcomes?",
    "Should there be limits on emergency room visits?",
    "What role should schools play in children's health?",
    "Should there be mandatory health screenings for all adults?",
    "How do we balance individual choice with public health?",
    "Should there be limits on medical procedures based on age?",
    "What role should community gardens play in public health?",
    "Should there be mandatory addiction treatment programs?",
    "How important is work-life balance for health outcomes?",
  ],
  education: [
    "Should education be standardized or personalized for each student?",
    "What role should technology play in classroom learning?",
    "Should students be grouped by ability or kept in mixed classes?",
    "How important are standardized tests for measuring student success?",
    "Should schools focus more on academic or life skills?",
    "What role should parents play in their children's education?",
    "Should college education be free for everyone?",
    "How important is early childhood education for later success?",
    "Should schools have mandatory uniforms?",
    "What role should creativity play in academic curricula?",
    "Should students have more say in their educational choices?",
    "How important is physical education in overall development?",
    "Should schools teach financial literacy as a core subject?",
    "What role should competition play in educational environments?",
    "Should homework be mandatory or optional?",
    "How important is multicultural education in schools?",
    "Should schools focus on preparing students for jobs or citizenship?",
    "What role should online learning play in traditional education?",
    "Should teachers be paid based on student performance?",
    "How important is arts education for student development?",
    "Should schools have mandatory community service requirements?",
    "What role should peer tutoring play in learning?",
    "Should students be allowed to choose their own learning pace?",
    "How important is critical thinking versus memorization?",
    "Should schools teach emotional intelligence as a subject?",
    "What role should extracurricular activities play in education?",
    "Should education be focused on local or global perspectives?",
    "How important is teacher training for educational quality?",
    "Should schools have mandatory environmental education?",
    "What role should student feedback play in teacher evaluation?",
    "Should education be primarily public or private?",
    "How important is classroom size for learning outcomes?",
    "Should schools teach coding as a basic literacy skill?",
    "What role should project-based learning play in curricula?",
    "Should students be required to learn multiple languages?",
    "How important is collaboration versus individual achievement?",
    "Should schools have mandatory meditation or mindfulness programs?",
    "What role should career counseling play in high school?",
    "Should education be lifelong or concentrated in youth?",
    "How important is hands-on learning versus theoretical knowledge?",
    "Should schools teach philosophy and ethics to all students?",
    "What role should assessment play in learning?",
    "Should education focus on depth or breadth of knowledge?",
    "How important is social-emotional learning in schools?",
    "Should schools have mandatory entrepreneurship education?",
    "What role should cultural education play in curricula?",
    "Should students be allowed to fail and repeat grades?",
    "How important is outdoor education for child development?",
    "Should schools teach media literacy as a core skill?",
    "What role should student-led learning play in education?",
  ],
  culture: [
    "Should cultural traditions be preserved or allowed to evolve naturally?",
    "How important is cultural diversity in modern society?",
    "Should art be accessible to everyone or remain elite?",
    "What role should government play in supporting the arts?",
    "Should cultural appropriation be regulated or accepted?",
    "How important is preserving indigenous cultures?",
    "Should there be limits on cultural expression for social harmony?",
    "What role should popular culture play in education?",
    "Should museums return artifacts to their countries of origin?",
    "How important is learning about other cultures?",
    "Should there be mandatory cultural education in schools?",
    "What role should social media play in cultural exchange?",
    "Should cultural funding prioritize traditional or contemporary arts?",
    "How important is cultural identity in personal development?",
    "Should there be limits on cultural practices that conflict with human rights?",
    "What role should festivals play in community building?",
    "Should cultural heritage sites be protected from development?",
    "How important is multilingualism for cultural preservation?",
    "Should there be cultural quotas in media representation?",
    "What role should tourism play in cultural preservation?",
    "Should cultural education be mandatory for immigrants?",
    "How important is intergenerational cultural transmission?",
    "Should there be limits on commercializing cultural practices?",
    "What role should literature play in cultural understanding?",
    "Should cultural differences be celebrated or minimized?",
    "How important is cultural authenticity in a globalized world?",
    "Should there be protection for minority cultural practices?",
    "What role should food culture play in identity?",
    "Should cultural exchange programs be mandatory in schools?",
    "How important is cultural competency in professional settings?",
    "Should there be limits on cultural stereotyping in media?",
    "What role should oral traditions play in modern education?",
    "Should cultural practices adapt to modern values?",
    "How important is cultural continuity versus innovation?",
    "Should there be international protection for cultural rights?",
    "What role should cultural institutions play in democracy?",
    "Should cultural funding be based on popularity or artistic merit?",
    "How important is local culture versus global culture?",
    "Should there be mandatory respect for all cultural practices?",
    "What role should cultural mentorship play in communities?",
    "Should cultural education focus on similarities or differences?",
    "How important is cultural pride for individual wellbeing?",
    "Should there be limits on cultural criticism?",
    "What role should cultural ambassadors play in international relations?",
    "Should cultural preservation take priority over urban development?",
    "How important is cultural accessibility for people with disabilities?",
    "Should cultural values influence law and policy?",
    "What role should cultural celebrations play in workplace environments?",
    "Should cultural education include controversial historical topics?",
    "How important is cultural expression for human dignity?",
  ],
  science: [
    "Should scientific research be driven by curiosity or practical applications?",
    "How important is peer review in validating scientific discoveries?",
    "Should there be limits on genetic engineering research?",
    "What role should scientists play in public policy decisions?",
    "Should scientific research be publicly funded or privately sponsored?",
    "How important is reproducibility in scientific studies?",
    "Should there be mandatory science education for all citizens?",
    "What role should ethics play in scientific experimentation?",
    "Should animal testing be completely banned?",
    "How important is international collaboration in scientific research?",
    "Should scientific findings be communicated directly to the public?",
    "What role should artificial intelligence play in scientific discovery?",
    "Should there be limits on human enhancement technologies?",
    "How important is scientific literacy for democratic participation?",
    "Should controversial scientific research be restricted?",
    "What role should citizen science play in research?",
    "Should scientific journals be freely accessible to everyone?",
    "How important is interdisciplinary research for scientific progress?",
    "Should there be mandatory disclosure of research funding sources?",
    "What role should scientific uncertainty play in policy-making?",
    "Should there be global governance of emerging scientific technologies?",
    "How important is basic research versus applied research?",
    "Should scientific education focus on facts or methods?",
    "What role should scientific models play in understanding reality?",
    "Should there be limits on research that could be used for weapons?",
    "How important is diversity in scientific research teams?",
    "Should scientific research be subject to democratic oversight?",
    "What role should scientific institutions play in society?",
    "Should there be mandatory scientific impact assessments?",
    "How important is scientific independence from political influence?",
    "Should emerging technologies be regulated before full understanding?",
    "What role should scientific education play in combating misinformation?",
    "Should there be limits on human subjects research?",
    "How important is scientific transparency for public trust?",
    "Should scientific research prioritize developed or developing world needs?",
    "What role should scientific advisory boards play in government?",
    "Should there be mandatory ethics training for scientists?",
    "How important is scientific communication for research funding?",
    "Should scientific research be influenced by social justice concerns?",
    "What role should scientific evidence play in legal proceedings?",
    "Should there be limits on publishing research with dual-use potential?",
    "How important is scientific education for economic development?",
    "Should scientific research be subject to community consent?",
    "What role should scientific institutions play in environmental protection?",
    "Should there be international standards for scientific research ethics?",
    "How important is scientific skepticism for progress?",
    "Should scientific research be guided by precautionary principles?",
    "What role should scientific visualization play in public understanding?",
    "Should there be mandatory scientific training for policymakers?",
    "How important is scientific humility in advancing knowledge?",
  ],
  sports: [
    "Should performance-enhancing drugs be allowed in professional sports?",
    "How important is winning versus participation in youth sports?",
    "Should there be salary caps in professional sports?",
    "What role should sports play in education?",
    "Should transgender athletes compete in gender-specific categories?",
    "How important is fair play versus competitive advantage?",
    "Should college athletes be paid for their participation?",
    "What role should technology play in sports officiating?",
    "Should there be age limits for professional athletes?",
    "How important is physical education in schools?",
    "Should sports betting be legal and regulated?",
    "What role should sports play in international diplomacy?",
    "Should there be mandatory drug testing for all athletes?",
    "How important is specialization versus multi-sport participation?",
    "Should violent sports like boxing be banned?",
    "What role should parents play in youth sports?",
    "Should professional sports teams be publicly funded?",
    "How important is mental health support for athletes?",
    "Should there be limits on contact sports for children?",
    "What role should sports play in community building?",
    "Should esports be considered legitimate competitive sports?",
    "How important is gender equality in sports coverage?",
    "Should there be mandatory concussion protocols in all sports?",
    "What role should sports play in physical rehabilitation?",
    "Should there be limits on training intensity for young athletes?",
    "How important is sportsmanship versus winning at all costs?",
    "Should sports stadiums be built with public money?",
    "What role should adaptive sports play for people with disabilities?",
    "Should there be mandatory life skills education for professional athletes?",
    "How important is cultural representation in international sports?",
    "Should there be limits on sports specialization at young ages?",
    "What role should sports play in promoting social change?",
    "Should there be mandatory retirement ages for contact sports?",
    "How important is coaching certification for youth sports?",
    "Should there be equal prize money in all gendered sports competitions?",
    "What role should sports psychology play in athlete development?",
    "Should there be limits on advertising during sports broadcasts?",
    "How important is accessibility in sports facilities?",
    "Should there be mandatory character education through sports?",
    "What role should sports play in post-conflict reconciliation?",
    "Should there be limits on sports-related travel for environmental reasons?",
    "How important is fan behavior regulation at sporting events?",
    "Should there be mandatory financial literacy education for professional athletes?",
    "What role should sports play in addressing social inequality?",
    "Should there be limits on sports merchandise commercialization?",
    "How important is injury prevention versus performance enhancement?",
    "Should there be mandatory community service for professional athletes?",
    "What role should traditional games play in modern sports culture?",
    "Should there be global standards for sports governance?",
    "How important is lifelong participation in sports for public health?",
  ],
};
